Go1vs1noob/feat/yaml editor
frostsergei/battery-devices-master pull request #22
Opened 2024-03-11 13:18 UTC by go1vs1noob

2024-03-11 14:51 UTC, IlyaTsaplin reviewed
lgtm (только вопрос с переносом и проблемами)

2024-03-11 14:51 UTC, IlyaTsaplin commented on docs/api/api.yaml
> +      description: "Echo request/response body\n            "
А зачем тут перенос строки и пробелы?

2024-03-11 17:26 UTC, purposelessness commented on docs/api/api.yaml
> +      description: "Echo request/response body\n            "
А это вот потому что [команда sed](https://github.com/frostsergei/battery-devices-master/blob/cb07de002b04966380d47cd19ca8012675efb2ae/Makefile#L6) не работает на винде. И [в этом issue](https://github.com/frostsergei/battery-devices-master/issues/21) её нужно пофиксить.

Но вообще, да, я бы убрал тогда изменения api.yaml из коммита :)

2024-03-11 18:17 UTC, IlyaTsaplin approved these changes

2024-03-11 20:42 UTC, purposelessness commented
Так-с, а я немного не понял, а зачем нам редактор ямля на странице? о_0

2024-03-11 21:14 UTC, go1vs1noob commented
как я понял, чтобы дрэг энд дроп не добавлять, и можно было прям там редактировать, воооот... а ваще мне сказали я и сделал

2024-03-11 21:14 UTC, go1vs1noob commented
> Так-с, а я немного не понял: а зачем нам редактор ямля на странице? о_0

как я понял, чтобы дрэг энд дроп не добавлять, и можно было прям там редактировать, воооот... а ваще мне сказали я и сделал

2024-03-11 21:15 UTC, go1vs1noob commented
> Так-с, а я немного не понял: а зачем нам редактор ямля на странице? о_0

как я понял, чтобы дрэг энд дроп не добавлять, и можно было прям там редактировать, воооот...

2024-03-12 06:45 UTC, purposelessness commented
> как я понял, чтобы дрэг энд дроп не добавлять, и можно было прям там редактировать, воооот... 

Так а зачем юзеру редактировать ямлик? 😐 Он как раз выбирает готовые настройки (или драг-н-дропает), отсылает на бек, после чего к нему приходит готовый ямлик, по которому строится визуал — и пользователь уже кнопочками настраивает бд.... 🤕
@IlyaTsaplin ?

2024-03-12 07:20 UTC, IlyaTsaplin commented
> Так а зачем юзеру редактировать ямлик?

Это будет форма для редактирования конфигурационных ямлов: конфиг формы и параметров. Т.е. ей не юзер, а админ будет пользоваться. Потом её надо будет на свою страничку унести, по-хорошему ещё закрыть страничку от обычного юзера. Но тут уже появляются задачи с ролями пользователей и авторизацией, они не в приоритете

2024-03-12 07:41 UTC, purposelessness requested changes

2024-03-12 07:41 UTC, purposelessness commented on client/src/app/app.component.ts
> +  onRecieveValidYAMLText(newText: string): void {
`onReceiveValidYamlText`

2024-03-12 07:41 UTC, purposelessness commented on client/src/app/app.component.ts
> +  onRecieveValidYAMLText(newText: string): void {
Нужно и в настройках форматтера выставить: пустые строчки между функциями

2024-03-12 07:41 UTC, purposelessness commented on client/src/app/yaml-editor/yaml-editor.component.ts
> +import { Ace, edit } from 'ace-builds';
Стоит отделить пустой строкой импорты ангуляра и сторонних библиотек

2024-03-12 07:41 UTC, purposelessness commented on client/src/app/yaml-editor/yaml-editor.component.ts
> +  };
Модификаторы доступа и тип для каждого поля

2024-03-12 07:41 UTC, purposelessness commented on client/src/app/yaml-editor/yaml-editor.component.ts
> +      const yamlException = e as yamlParser.YAMLException;
Тогда уж не проще сразу его ловить?

2024-03-12 07:41 UTC, purposelessness commented on client/src/app/yaml-editor/yaml-editor.component.ts
> +  emitYamlText() {
`public`?

2024-03-12 07:51 UTC, go1vs1noob commented on client/src/app/yaml-editor/yaml-editor.component.ts
> +      const yamlException = e as yamlParser.YAMLException;
тайпскрипт ругается

2024-03-13 08:21 UTC, go1vs1noob commented on client/src/app/yaml-editor/yaml-editor.component.ts
> +import { Ace, edit } from 'ace-builds';
линтер не даёт так делать

2024-03-13 18:19 UTC, purposelessness approved these changes

2024-03-13 18:19 UTC, merged

2024-03-13 18:20 UTC, purposelessness commented on client/src/app/yaml-editor/yaml-editor.component.ts
> +import { Ace, edit } from 'ace-builds';
Решили, что пофиксим чуть позже.