feat server: add yaml handle
frostsergei/battery-devices-master pull request #24
Opened 2024-03-13 17:21 UTC by Allonario

2024-03-14 09:06 UTC, purposelessness requested changes

2024-03-14 09:06 UTC, purposelessness commented on server/Controllers/YamlController.cs
> +    public async Task<IActionResult> Post([FromBody] EchoBody body)
Создай отдельную структуру для запроса к этой ручке

2024-03-14 09:06 UTC, purposelessness commented on server/Controllers/YamlController.cs
> +    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
Вынеси, пожалуйста, `ErrorResponse` в отдельный файлик

2024-03-15 16:57 UTC, Allonario commented on server/Controllers/YamlController.cs
> +    public async Task<IActionResult> Post([FromBody] EchoBody body)
Можешь подробнее описать, что и как ты имеешь в виду в качестве логов?

2024-03-15 17:08 UTC, purposelessness commented on server/Controllers/YamlController.cs
> +    public async Task<IActionResult> Post([FromBody] EchoBody body)
Типа какие-нибудь дебаги, мол, создали папку или успешно завершили запрос. 
Error, если случилась внутренняя ошибка, и warning, если клиент ввёл некорректные данные.

Ну, если это несложно делается..

2024-03-15 17:09 UTC, Allonario commented on server/Controllers/YamlController.cs
> +    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
Может и EchoResponse тоже, только дать более общее название, для положительных ответов клиенту, которые не несут в себе сложную структуру, а просто сообщение о положительном результате запроса?

2024-03-15 18:02 UTC, purposelessness commented on server/Controllers/YamlController.cs
> +    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
Ммм.... Ну можно + переименовать на что-то типа `TextMessage`.

2024-03-16 09:17 UTC, purposelessness approved these changes

2024-03-17 09:11 UTC, go1vs1noob approved these changes

2024-03-17 10:32 UTC, mSulimenko approved these changes

2024-03-18 18:06 UTC, merged