Frontend first prototype (issue #1)
frostsergei/battery-devices-master pull request #6
Opened 2024-02-23 07:44 UTC by mSulimenko

2024-02-23 10:32 UTC, purposelessness requested changes

2024-02-23 10:32 UTC, purposelessness commented on client/src/app/app.component.ts
> +    });
Насколько я помню, более правильно ~~(стильно, модно, современно)~~ передавать в качестве аргумента словарик вида
```ts
numbers$.subscribe({
  next: value => console.log('Observable emitted the next value: ' + value),
  error: err => console.error('Observable emitted an error: ' + err),
  complete: () => console.log('Observable emitted the complete notification')
});
```

2024-02-23 10:32 UTC, purposelessness commented on client/src/app/app.component.ts
> +  constructor(private http: HttpClient) {}
`readonly`?

2024-02-23 10:32 UTC, purposelessness commented on client/src/main.ts
> +import { AppModule } from './app/app.module';
Отступ между импортами фреймворка и пользовательскими файлами

2024-02-23 10:32 UTC, purposelessness commented on client/src/main.ts
> +import { AppModule } from './app/app.module';
Мы уверены, что хотим относительными путями всё импортить? Думаю, стоит сразу задуматься о настройке конфига для возможности использования абсолютных путей.

2024-02-23 10:32 UTC, purposelessness commented on client/src/app/app.module.ts
> +import { AppComponent } from './app.component';
Отступ между импортами фреймворка и пользовательскими файлами

2024-02-23 10:32 UTC, purposelessness commented on client/src/app/app.module.ts
> +import { HttpClientModule } from '@angular/common/http';
Каким образом сортировка работает? 🤔 По имени импортируемого файла или по импортируемым символам?

2024-02-23 10:32 UTC, purposelessness commented on client/src/app/app.component.ts
> +    this.http.get('https://localhost:8080/ping').subscribe(response => {
Наброс на будущее: стоило бы с умом подойти к организации клиентов и url-констант.

2024-02-23 10:32 UTC, purposelessness commented on client/.gitignore
> +.idea/
В gitignore добавил, но из коммита забыл удалить.

2024-02-23 10:32 UTC, purposelessness commented
Ещё нужно бы потом подумать, как затащить автопроверки какие-нибудь (как минимум, на форматирование)....

2024-02-23 11:40 UTC, go1vs1noob commented on client/src/main.ts
> +import { AppModule } from './app/app.module';
> Мы уверены, что хотим относительными путями всё импортить? Думаю, стоит сразу задуматься о настройке конфига для возможности использования абсолютных путей.

Зачем? Может я чего-то не понял, но angular же бандл сам потом сгенерирует и с путями проблем быть не должно, или есть какие-то подводные ещё?

2024-02-23 11:42 UTC, go1vs1noob commented on client/src/app/app.module.ts
> +import { HttpClientModule } from '@angular/common/http';
> Каким образом сортировка работает? 🤔 По имени импортируемого файла или по импортируемым символам?

Здесь тоже не понял, нужно импортировать модули в алфавитном порядке?

2024-02-23 12:12 UTC, purposelessness commented on client/src/main.ts
> +import { AppModule } from './app/app.module';
Не, я про то, что можно [установить в конфиге условный *якорь*](https://github.com/purposelessness/stock-market-vue/blob/1a23985cc5224002bd351788236a7c732f3bb288/tsconfig.json#L13), который бы при компиляции ресолвился в относительный путь. 
И в коде бы писали вместо относительного пути `../../../component/foo/bar/...` абсолютный — `~/component/foo/bar/...`.

2024-02-23 12:14 UTC, purposelessness commented on client/src/app/app.module.ts
> +import { HttpClientModule } from '@angular/common/http';
Мне интересно просто: форматтер так расставил импорты или же автор.

2024-02-23 13:19 UTC, go1vs1noob commented on client/src/app/app.module.ts
> +import { HttpClientModule } from '@angular/common/http';
Аа, у меня лично просто когда красным подчеркивает какой-то модуль (не импортирован) - нажимаю "ctrl" + "." и импорт сам дописывается. В каком порядке нажимаешь - в таком порядке и импорт

2024-02-23 13:43 UTC, purposelessness commented on client/src/app/app.module.ts
> +import { HttpClientModule } from '@angular/common/http';
> Аа, у меня лично просто когда красным подчеркивает какую-то штуку из модуля, который не импортирован - нажимаю "ctrl" + "." и импорт сам дописывается. В каком порядке нажимаешь - в таком порядке и импорт

Ага, это конечно, но если прожать ctrl+alt+l (cmd+alt+l) в webstorm, то оно и отформатируется, согласно выставленным настройкам. Либо в командной строке прописать какой-нибудь tsfmt

2024-03-05 14:39 UTC, mSulimenko commented
Не изменил адресацию, так как не до конца понял, зачем в нашем проекте это нужно, и вообще решили ли мы так делать. Если нужно и решили, то доделаю

2024-03-05 15:15 UTC, purposelessness commented
[Прочитай, пожалуйста, про типы коммитов](https://sentenz.github.io/guide/internal/convention/conventional-commits.html#12-types) — объяснено, когда писать `feat`, когда `refactor`, `fix` и т. п.

2024-03-05 15:24 UTC, purposelessness approved these changes

2024-03-05 15:24 UTC, purposelessness commented on client/.gitignore
> +# See http://help.github.com/ignore-files/ for more about ignoring files.
Добавь ещё `.vscode`, оно ни к чему нам.

2024-03-05 15:24 UTC, purposelessness commented on client/.gitignore
> +# See http://help.github.com/ignore-files/ for more about ignoring files.
Хотя ладно, потом сам поправлю. Всё равно мне всё перелопатить нужно будет.

2024-03-06 15:53 UTC, go1vs1noob approved these changes

2024-03-06 18:10 UTC, merged